### ISSUE TITLE
[Self-hosted] Failed fetching releases (401)

### ISSUE THREAD

**Issue by tlinhh2** [opentofu/setup-opentofu#32]
Hi team,

I am trying to use OpenTofu in **self-hosted** runner. However, it does not work:

```bash
Error: Error: failed fetching releases (401)
Error: failed fetching releases (401)
```

Here is my very simple setup:

```yaml
name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: opentofu/setup-opentofu@v1
```

Please kindly let me know how to bypass this situation. Thank you for your help!
