### ISSUE TITLE
Improvement for CICD acceptance tests

### ISSUE THREAD

**Issue by littlejo** [opentofu/setup-opentofu#36]
My code is:
```
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
      - run: go mod download
      - env:
          TF_ACC: "1"
          TF_ACC_PROVIDER_NAMESPACE: "hashicorp"
          TF_ACC_PROVIDER_HOST: "registry.opentofu.org"
        run: TF_ACC_TERRAFORM_PATH=$(which tofu) go test -v -cover ./cilium
        timeout-minutes: 10
```

Could you create automatically environment variable?

Like that, my code would be clean:
```
      - uses: opentofu/setup-opentofu@v1
        with:
          tofu_wrapper: false
          acceptance_test: true
      - run: go mod download
      - run: go test -v -cover ./cilium
        timeout-minutes: 10
```
