### ISSUE TITLE
Update GitHub Action Branding from Legacy Terraform Color Scheme

### ISSUE THREAD

**Issue by RoseSecurity** [opentofu/setup-opentofu#4]
## What and Why: 

- Change legacy GitHub Action branding to reflect OpenTofu color scheme:

**Before:**

```yaml
branding:
  icon: 'terminal'
  color: 'purple'
```

**After:**

```yaml
branding:
  icon: 'trending-up'
  color: 'yellow'
```
